### ISSUE TITLE
Support of Javalin 6.x

### ISSUE THREAD

**Issue by marcelbaumann** [mvysny/vaadin-boot#23]
Hello

Are you planning to support Javalin 6.x in the next future.

Javalin has changed their API and the example in the README are no more working.

If desired, I could try to modify the examples to support the newer version if you have no activities under way.

Sincerely

**Comment by ev-fi** [comment]
Hi, I would love to! I even tried (and failed since the api is quite different ). I have little time on my hands at the moment; please feel free to work on this if you’d like.👍

**Comment by mvysny** [comment]
I've started working on this in the feature/23-javalin6 branch. Unfortunately, Javalin fails to initialize with
```
Caused by: java.lang.NoSuchMethodError: 'java.util.Map org.eclipse.jetty.http.MimeTypes.getInferredEncodings()'
	at io.javalin.jetty.JettyServer.<init>(JettyServer.kt:39)
	at io.javalin.Javalin.lambda$new$0(Javalin.java:39)
```
Investigating.

**Comment by mvysny** [comment]
Filed as https://github.com/javalin/javalin/issues/2155 .

**Comment by mvysny** [comment]
Decision from upstream: Javalin 6 won't support Jetty 12. We'll have to wait for Javalin 7.

**Comment by marcelbaumann** [comment]
Hello

Great. I will wait. I got the same exception. FYI, the servlet code for Javalin 6.1 which compile on my example is 

```
@WebServlet(name = "RestServlet", urlPatterns = {"/rest/*"})
public class ApiServlet extends HttpServlet {
    private final transient Servlet javalin = Javalin.create().get("/rest/hello", ctx -> ctx.result("Hello!"))
        .javalinServlet();


    @Override
    protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        javalin.service(req, resp);
    }
}
```

Cheers
