### ISSUE TITLE
False HeadlessException

### ISSUE THREAD

**Issue by Osiris-Team** [mvysny/vaadin-boot#24]
```sh
java.awt.HeadlessException
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(HeadlessGraphicsEnvironment.java:52)
...
```
Just switched to jetty / vaadin-boot, from spring-boot, in a project of mine where before this exception was not thrown.
I require access to the graphics stuff, so removing that code won't be a workaround, I need to find the root cause for this.
This happens when running the Main class via my IDE.

You should be able to reproduce this issue in the starter project by simply adding this somewhere:
```java
                System.setProperty("java.awt.headless", "false");
                GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                GraphicsDevice[] screens = ge.getScreenDevices();
```

**Comment by mvysny** [comment]
Interesting! I've reproduced the same issue when pasting your code to a view's constructor. Things fixed itself when I moved the `System.setProperty("java.awt.headless", "false");` command to main as follows:
```java
public class Main {
    public static void main(String[] args) throws Exception {
        System.setProperty("java.awt.headless", "false");
        new VaadinBoot().run();
    }
}
```
I know that Vaadin is using some 2D code from awt to calculate/resize PWA icons. Maybe at that point the "java.awt.headless" setting is "set in place" and any future changes are ignored.

Please let me know whether this fix  works for you.

**Comment by Osiris-Team** [comment]
Yep, that fixed it! Thanks.
